version: "3.8"
name: postgres-sql

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: MikeDST
      POSTGRES_PASSWORD: 12345asd
      POSTGRES_DB: TestDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: